### ISSUE TITLE
Question: Compatibility error during entity manager bean inizialization `java.lang.NoSuchFieldError: BEFORE_TRANSACTION_COMPLETION`

### ISSUE THREAD

**Issue by p4535992** [ghusta/matrice-versions-spring-hibernate#2]
Sorry to bother i must be very stupid... and this is  really important for me...

I followed the tables, but it seems I keep having some compatibility problem with the **spring-orm 5.3.27**, no matter how hard I try I keep getting this error below the dependencies I am using:

```
 Error creating bean with name 'entityManagerFactory' defined in file [/usr/local/tomcat/webapps/alfresco/WEB-INF/classes/alfresco/module/pasharing-ext-port-access-management-repo/context/service-pasharing-ext-port-access-management-beans-context.xml]: Invocation of init method failed; nested exception is java.lang.NoSuchFieldError: BEFORE_TRANSACTION_COMPLETION
```

Hibernate Version:
```
		<dependency>
		    <groupId>org.hibernate</groupId>
		    <artifactId>hibernate-core</artifactId>
		    <version>5.4.23.Final</version>
		</dependency>
```
Spring Data JPA version:

```
                <dependency>
		    <groupId>org.springframework.data</groupId>
		    <artifactId>spring-data-jpa</artifactId>
		    <version>2.2.13.RELEASE</version><!-- maybe  is better 2.7.12 (because it use the spring version 5.3.27) ? -->
		</dependency>
```
Spring ORM version:

```
<dependency>
    <groupId>org.springframework</groupId>
    <artifactId>spring-orm</artifactId>
    <version>5.3.27</version>
</dependency>
```

is this combination ok ?

**Comment by p4535992** [comment]
Nevermind i'm stupid.... i have two version of the hibernate-core on the project

**Comment by ghusta** [comment]
Hello
No problem !
Thank you for your interest.

By the way, I did another project at : https://github.com/ghusta/matrice-versions-spring-boot-dependencies
where I maintain a matrix with Spring Boot versions, listing what are the versions of spring-fwk / spring-data-jpa / hibernate orm, etc.
It might be use useful to try to align your versions on a Spring Boot version, for consistency.

Based on your example, you could try to align your dependencies on Spring Boot 2..4.x or 2.5.x (not maintained anymore of course -> https://spring.io/projects/spring-boot#support).
